#!/bin/sh

if [ -f "/usr/local/bin/junglediskserver" ]; then
bin_name="junglediskserver"
elif [ -f "/usr/local/bin/mysecurebackupserver" ]; then
bin_name="mysecurebackupserver"
else
echo "Can't find Jungledisk, is it installed correctly?"
exit 1
fi

process=`ps auxwww | grep $bin_name | awk '{print $11}'`
if [ -z "$process" ]; then
	echo "Couldn't find jungledisk running, starting jungledisk."
	/etc/init.d/$bin_name start
else
exit 0
fi
